In [ ]:
import numpy as np

In [ ]:
array1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
array2 = np.array([[11,12,13],[14,15,16],[17,18,19]])
print(array2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]


1.1 Addition

In [ ]:
resultarray= array1 + array2
print("\n Using Operator:\n",resultarray)
resultarray=np.add(array1,array2)
print("\n Using Numpy function:\n",resultarray)


 Using Operator:
 [[12 14 16]
 [18 20 22]
 [24 26 28]]

 Using Numpy function:
 [[12 14 16]
 [18 20 22]
 [24 26 28]]


In [ ]:
resultarray= array1 - array2
print("\n Using Operator:\n",resultarray)
resultarray=np.subtract(array1,array2)
print("\n Using Numpy function:\n",resultarray)


 Using Operator:
 [[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]

 Using Numpy function:
 [[-10 -10 -10]
 [-10 -10 -10]
 [-10 -10 -10]]


In [ ]:
resultarray= array1 * array2
print("\n Using Operator:\n",resultarray)
resultarray=np.multiply(array1,array2)
print("\n Using Numpy function:\n",resultarray)


 Using Operator:
 [[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]

 Using Numpy function:
 [[ 11  24  39]
 [ 56  75  96]
 [119 144 171]]


In [ ]:
resultarray= array1 / array2
print("\n Using Operator:\n",resultarray)
resultarray=np.divide(array1,array2)
print("\n Using Numpy function:\n",resultarray)


 Using Operator:
 [[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]

 Using Numpy function:
 [[0.09090909 0.16666667 0.23076923]
 [0.28571429 0.33333333 0.375     ]
 [0.41176471 0.44444444 0.47368421]]


In [ ]:
resultarray= array1 % array2
print("\n Using Operator:\n",resultarray)
resultarray=np.mod(array1,array2)
print("\n Using Numpy function:\n",resultarray)


 Using Operator:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 Using Numpy function:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


Dot

In [ ]:
resultarray= np.dot(array1,array2)
print(resultarray)

[[ 90  96 102]
 [216 231 246]
 [342 366 390]]


**Transpose**




In [ ]:
resultarray= np.transpose(array1)
print(resultarray)
resultarray=array1.transpose()
print(resultarray)

[[1 4 7]
 [2 5 8]
 [3 6 9]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


2. Horizontal and Vertical Stacking

2.1 Horizontal Staking

In [ ]:
resultarray= np.hstack((array1,array2))
resultarray

array([[ 1,  2,  3, 11, 12, 13],
       [ 4,  5,  6, 14, 15, 16],
       [ 7,  8,  9, 17, 18, 19]])

2.2 Vertical Staking

In [ ]:
resultarray= np.vstack((array1,array2))
resultarray

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

stacking two 3d arrays

In [ ]:
c = np.stack((array1,array2),axis=1)
print(c)

[[[ 1  2  3]
  [11 12 13]]

 [[ 4  5  6]
  [14 15 16]]

 [[ 7  8  9]
  [17 18 19]]]


stacking two 1d arrays

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
 
# Stacking 2 1-d arrays
c = np.stack((a, b),axis=0)
print(c)

[[1 2 3]
 [4 5 6]]


In [ ]:
x=np.array([[1,2,3],
            [4,5,6]])
 
y=np.array([[7,8,9],
            [10,11,12]])
           
np.stack((x,y),axis=1)

array([[[ 1,  2,  3],
        [ 7,  8,  9]],

       [[ 4,  5,  6],
        [10, 11, 12]]])

3.Custom sequence *Generation*

Get the Shape of an Array

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


Reshape From 1-D to 2-D

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


Make a copy, change the original array, and display both arrays:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


Make a view, change the original array, and display both arrays:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


Make a view, change the view, and display both arrays:

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]




---

**Filtering Arrays**


---



In [2]:
import numpy as np
arr = np.array([41,42,43,44])
x= [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]




---

**Custum Sequence Generation**


---



In [5]:
import numpy as np

list1 = [x for x in range(0, 101,2)]

a = np.array(list1)

print(a)
print(type(list1))
print(type(a))

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
<class 'list'>
<class 'numpy.ndarray'>


In [11]:
import numpy as np
b = np.arange(50, 0 ,-1)
print(b)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3
  2  1]


In [12]:
import numpy as np
b = np.arange(50, 0 ,-1).reshape(5,10)

print(b)

[[50 49 48 47 46 45 44 43 42 41]
 [40 39 38 37 36 35 34 33 32 31]
 [30 29 28 27 26 25 24 23 22 21]
 [20 19 18 17 16 15 14 13 12 11]
 [10  9  8  7  6  5  4  3  2  1]]


In [ ]:
empty() function is used to return new array with given shape

In [14]:
nparray = np.empty((3,3), int)

print(nparray)

[[       48693280               0 140371442946608]
 [140371445022960 140370192999136 140371422047088]
 [140371444825856 140370192991456              96]]


equally spaced numbers within given range

In [17]:
z = np.linspace(0, 100 ,6)

print (z)

[  0.  20.  40.  60.  80. 100.]


search an array for certain value returns index that get a match

In [21]:
arr= np.array([10, 20 ,30 ,4,5,4,4])

x= np.where(arr==4)

print(x)

(array([3, 5, 6]),)


In [22]:
import numpy as np

arr= np.array([10, 20,33 ,30,73 ,24,59,44,47])

x= np.where(arr%2==0)

print(x)

(array([0, 1, 3, 5, 7]),)


Search Sorted Method

we can give them from where to search by side="right" or side="left"

In [31]:
import numpy as np

arr = np.array([6,7,8,9])

x = np.searchsorted(arr , [7,8], side='left')
y = np.searchsorted(arr , 8, side='left')
print(x,y)

[1 2] 2


Multiply value search

In [28]:
import numpy as np

arr = np.array([10 ,30 , 50, 70])

x = np.searchsorted(arr ,[20, 40, 60])

print(arr)
print(x)

[10 30 50 70]
[1 2 3]


In [33]:
array1 = np.array([1,2,3,12,5,7,0])
print(np.count_nonzero(array1))#returns totall non zero elements
print(np.nonzero(array1))#index
print(array1.size)#total elements

6
(array([0, 1, 2, 3, 4, 5]),)
7


Statistical and Mathemathical Operations

In [35]:
array1 = np.array([1,2,3,4,5,9,6,7,8,9,9])
# standerd deviation
print(np.std(array1))
#Minimum
print(np.min(array1))
#summation
print(np.sum(array1))
#median
print(np.median(array1))
#mean
print(np.mean(array1))
#Mode
from scipy import stats

print("Most frequent element =",stats.mode(array1)[0])
print("Number of occarences =",stats.mode(array1)[1])
# variance
print(np.var(array1))

2.7990553306073913
1
63
6.0
5.7272727272727275
Most frequent element = [9]
Number of occarences = [3]
7.834710743801653


<ipython-input-35-cdf7a902e8ea>:15: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print("Most frequent element =",stats.mode(array1)[0])
<ipython-input-35-cdf7a902e8ea>:16: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  print("Number of occarences =",stats.mode(arr

**brodecasting**

In [36]:
a = np.array([1.0, 2.0, 3.0])
b = np.array([2.0, 2.0, 2.0])
a * b

array([2., 4., 6.])

In [38]:
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])
b = np.array([1.0, 2.0, 3.0])
a + b



array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [39]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis] + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [40]:
from numpy import array, argmin, sqrt, sum
observation = array([111.0, 188.0])
codes = array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])
diff = codes - observation    # the broadcast happens here
dist = sqrt(sum(diff**2,axis=-1))
argmin(dist)

0

In [42]:
import numpy as np 

a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print (c)

[ 10  40  90 160]


In [44]:
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print ('First array:') 
print (a )
print ('\n')  
   
print ('Second array:') 
print (b )
print ('\n')  
   
print ('First Array + Second Array') 
print (a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array:
[1. 2. 3.]


First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
